### ISSUE TITLE
How to get Koinify wallet 12 word passphrase

### ISSUE THREAD

**Issue by igorbarinov** [FactomProject/keymaker#1]
I signed up to Koinify today and do not see how to get the passphrase

**Comment by kitplummer** [comment]
Same here, trying to setup keymaker.

**Comment by carryforward** [comment]
Good question.  The passphrase will only be relevant if you sent in BTC between March 31 and May 15.  Signing up for koinify now will not get you factoids to add data into the system.

To develop, it is best to start in a sandbox environment.  https://github.com/FactomProject/FactomDocs/blob/master/developerSandboxSetup.md

To get data into Factom, Factoids need to be procured via the market.  Currently poloniex is the best place for this.

If you would like to do some development, I can send you a few factoids to get started if needed.
